//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlogs.WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BlogEntities : DbContext
    {
        public BlogEntities()
            : base("name=BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbBlogComment> tbBlogComments { get; set; }
        public virtual DbSet<tbBlogPost> tbBlogPosts { get; set; }
        public virtual DbSet<tbBlogUser> tbBlogUsers { get; set; }
        public virtual DbSet<tbBlogPublicUserComment> tbBlogPublicUserComments { get; set; }
    
        public virtual int spAddBlogUser(string blogUserName, string blogUserPassword, string blogUserEmailID)
        {
            var blogUserNameParameter = blogUserName != null ?
                new ObjectParameter("BlogUserName", blogUserName) :
                new ObjectParameter("BlogUserName", typeof(string));
    
            var blogUserPasswordParameter = blogUserPassword != null ?
                new ObjectParameter("BlogUserPassword", blogUserPassword) :
                new ObjectParameter("BlogUserPassword", typeof(string));
    
            var blogUserEmailIDParameter = blogUserEmailID != null ?
                new ObjectParameter("BlogUserEmailID", blogUserEmailID) :
                new ObjectParameter("BlogUserEmailID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddBlogUser", blogUserNameParameter, blogUserPasswordParameter, blogUserEmailIDParameter);
        }
    
        public virtual ObjectResult<spGetAllUsers_Result> spGetAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllUsers_Result>("spGetAllUsers");
        }
    
        public virtual ObjectResult<spGetBlogs_Result> spGetBlogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetBlogs_Result>("spGetBlogs");
        }
    
        public virtual ObjectResult<spGetBlogsByBlogPostID_Result> spGetBlogsByBlogPostID(Nullable<int> blogPostID)
        {
            var blogPostIDParameter = blogPostID.HasValue ?
                new ObjectParameter("BlogPostID", blogPostID) :
                new ObjectParameter("BlogPostID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetBlogsByBlogPostID_Result>("spGetBlogsByBlogPostID", blogPostIDParameter);
        }
    
        //public virtual ObjectResult<spGetValidateUser_Result> spGetValidateUser(string blogUserEmailID, string blogUserPassword)
        //{
        //    var blogUserEmailIDParameter = blogUserEmailID != null ?
        //        new ObjectParameter("BlogUserEmailID", blogUserEmailID) :
        //        new ObjectParameter("BlogUserEmailID", typeof(string));
    
        //    var blogUserPasswordParameter = blogUserPassword != null ?
        //        new ObjectParameter("BlogUserPassword", blogUserPassword) :
        //        new ObjectParameter("BlogUserPassword", typeof(string));
    
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetValidateUser_Result>("spGetValidateUser", blogUserEmailIDParameter, blogUserPasswordParameter);
        //}
    
        public virtual int spUpdateAdminUser(Nullable<int> blogUserID)
        {
            var blogUserIDParameter = blogUserID.HasValue ?
                new ObjectParameter("BlogUserID", blogUserID) :
                new ObjectParameter("BlogUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateAdminUser", blogUserIDParameter);
        }
    }
}
