//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlogs.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBlogUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBlogUser()
        {
            this.tbBlogComments = new HashSet<tbBlogComment>();
            this.tbBlogPosts = new HashSet<tbBlogPost>();
        }
    
        public int BlogUserID { get; set; }
        public string BlogUserName { get; set; }
        public string BlogUserPassword { get; set; }
        public string BlogUserEmailID { get; set; }
        public System.DateTime BlogUserCreatedDate { get; set; }
        public Nullable<bool> BlogIsAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBlogComment> tbBlogComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBlogPost> tbBlogPosts { get; set; }
    }
}
