//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlogs.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBlogPublicUserComment
    {
        public int BlogPUCommentID { get; set; }
        public string BlogPUComments { get; set; }
        public Nullable<int> BlogPUPostID { get; set; }
        public int BlogPUCommentsParentID { get; set; }
        public string BlogPUUserName { get; set; }
    
        public virtual tbBlogPost tbBlogPost { get; set; }
    }
}
