//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlogs.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBlogPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBlogPost()
        {
            this.tbBlogComments = new HashSet<tbBlogComment>();
            this.tbBlogPublicUserComments = new HashSet<tbBlogPublicUserComment>();
        }
    
        public int BlogPostID { get; set; }
        public string BlogPostTitle { get; set; }
        public string BlogPostBody { get; set; }
        public Nullable<System.DateTime> BlogPostDate { get; set; }
        public int BlogPostByUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBlogComment> tbBlogComments { get; set; }
        public virtual tbBlogUser tbBlogUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBlogPublicUserComment> tbBlogPublicUserComments { get; set; }
    }
}
